{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "forum-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "forum-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "DB_PASSWORD": "AgBTHxFS2d364w5u04FAB5GEoBCAGdq1ldrbkudVzTyrs8vYWf+4jbMo/dfwAwzfwg7WdjsrPL1pXWlxy24Y3Mw15xLcgTYHsz1nsI4l4J8g16IWJja+hxUj7q05B3hZ4bohgw0aVObjPPnPxw1BdtIhjq1qc45sDF0i11CTChalTMi07dg1HnRReAgDBGmrl1UWh8+6h9VmN5H8W23VxtNhAb9flvhgMcP19GfNtQWN7Wz8PciJrxoRX3zaF9z8B8sDtUgLQEBiGEsgCCWs4DEaeuoqW2ikQpnB6qQ0uiY4DsxbSsBWGCpqcT3KzdaSCA6eaHfZ11litZAUKJ3ZdmnzEmaVDx/muA4FqXhq4HJXius8Dhddbyv+M0CA9wc8TvPIQa4zU2Pg9NQEevTrbdHjWJS4ixHWgleWIQBe9DOmeb0lEeYYKxA+tDY7yVmRsve1P8ZecC3gZ/5QLdMV63FZ2HdfIPNkLRrFwvBGzAMgMjndzzzuAi7hyctHBBtIC5X3jUNzrQ80uQ7WcYC5HvYo0mDqctko3qthZNC87uYZ8udzwKdSvS/lYUCBDHJOXVrwu+n2IjwCKgrCvHu8YQEoY7KI3LJ3e2SigBx7g3rM/yCEkGgw4Os5X+nXJR07NlzzWCLHkFwXy/nYjJdQwgqJrbxtsS47YhDFtYhLzXRJv5gGMX5iWFg1nXKKjmCWJGCVcncv/1fSnw==",
      "DB_URL": "AgAJZbRJ3QlOQ07elqKn17P5UVoAlxTwRlYo++CpaHps5Tsw1X1s+7SJVghvqXL/2Y7flYKJfiKEAy5da6MD+US8Oo3kSL6vco0/PuFNmkDato30hKuyt7gfNZWevHvkORLyHVbS9NEZ+KVN/XjSK7un5EZzBCprTKAQK6TTBXwfUejv2TFbXwSMcxVE54a71p7mhHOmuQjZsdKEBS5Muv0G+zAAljAlAtoMHXYu2RdyBsbADGPKjE3Ny2NVfi+YBa24vK/pvk+Spd3x5R7X97czu0EOKCQyeTMtCuO+RgwxUk5zfxnCHUZxezA3wKr9Kunba2IKp2IvK1ZkCFu3xr2lKajjlYyQ1VWRYXkchQH/8SB/S9G4Cp+PPLWK36PXG4LbadGRYp9zUMOCl2zRl2HVT1XgDYeJs1VbuPFhQUIMNuBtxEApaLqqB1hJkUCZ1WRdhQwM8fP/kPF6nuAeF1lSagn3KKcxQzXw/7QTG4CvXeI6etY0BrdQs8qR6Z7yZHvjFZO2P+3/mRz8LRwIKTzsL7q3yrNysUP0JYWLgc6F5juQyi5VPzvA/ALAZFYW7gMQXXn9KOXNYiYJjKlIdWYcqiBE9Yfc+xMZqxfyE1yswJfT/fd6f6C0QzQ7Opk1LiQPElgJHdApPS/LUKze5U5T1XmqivFNAhftpSZg57Z2W85DN1rlFCOXi3mtMtX8qk3KR7+qn4ZWE+tT4AzBkaY5hiWzVDEKA8XNiBvmu4/mYtu8D4MVdJxW",
      "DB_USERNAME": "AgBvth+6dXD43Pa2VAp5hZOQgdseoEqDJEF/vmVSqGJdd4LqTUfYSMz7grJkpugws77u0gzmZU9uejLiw7sdeLMaKyYeq3yo3lbFDOkm8KJpQsu0mnU3LFMelLsGLkA73KS6WzYKyGTzjtBPdCKePp0cvt30LDl2pMmOKYu7j5XOvGxf8j0b5aOtU+URp8O+zY2n+dn96I2HRjyOFjEaI6l8TI8ncKSoJNOKlKl4ZNs3Yv6RQOBsAz0S2onC+SYOmkGBfEnpciM305Seu3eSkJdSd/4dGSm+DiXJg/MLSbFcLnI4sy9KqY9uMFEyDHAFdAyq0MyZ89ygHnI8UuOtRuQSOyIFxXn7IhjKCx8B9+Vz6L4NFUIr1sSfdRacw7T2aeLOCc/DqDdHU8BRkql7ccYYPXwJRr8fpTg3W9uqnP9/BIbDFwV1emT6G5DUf6X0VA9LtekcPsDJ7kJaVF+vl3gyWUkwvg3YqX91AIjQIDer7fJzDfW8/orTg+sLBX1ZuGZjsAlfusVIXZhsEsSEs6AUXJjYu3FroQnr8afsWHyOboRWIGmHTw5wo+rNNgCj/LJKHI0YRPKhWVGjJYFnn0y9HENefx6WIc1kaJn5fp6roUVd0ElhU1YxxL6OxovRcd/l6TZCGExIrQszq+1VPbd7jdFO/XsMDpCp6FgaVZFIqegrEf71VlzaZa336u3h4sl1z084pEGMYQ=="
    }
  }
}
