spring.application.name=forum_service
server.port=8082

# --- CẤU HÌNH KẾT NỐI DATABASE ---
# Vì bạn dùng --network=host, App sẽ tìm thấy DB tại localhost:5434
spring.datasource.url=jdbc:postgresql://localhost:5434/forum_db
spring.datasource.username=postgres
spring.datasource.password=Aa123456
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CẤU HÌNH JPA / HIBERNATE ---
# Tự động cập nhật cấu hình DB dựa trên Entity Java
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL ra console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Đảm bảo dùng đúng Dialect cho Postgres 17
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect