{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "forum-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "forum-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_DB": "AgAoU6zOLJ2mdk+swlSK3jWSLoxoc3Pu/GYcFv+Tjkwdvy1aYlVau7lTP+fAfH9nWoHaCTWVwYs+574EoV+9LwwLB5KCe3C46v1UjQ5fdU26NQbpujGgBKMpx2TgClYy8cYWNgSpuoXUh7BobP1ErNP9brPYtu4nTz8AZefB6juDnHg6q3b84G4d9DQKtCxeT9rJvcsHou3l/3OX6BeyJ7qmtGt1cVyqq51VvT+fHYuh+FwKkmjd9hNLodWojtUOS5rc5Q3P7YZYpe5WuxBKj8FG4JojRchA56PRFH+/APCiUFY0gXS/3hWso//+xb8+vAmId9DJFugIcCz73eInszEtIlRoiUj5enbdLL9MKgT/F++jkXHuHBdy8FYMLHWmPIXe5soNLPbMmEjkPE3ojOfUrLtDt9tLcGI72UncGscymOI0cbWSJKwTR3fW2sqox0X48maCZqWYYWFh4qPwYRE6ZaH8tcsHkscG5aq+iBM/leFYu3aQ10C0bMwv2SbmdZcORkRTrChGyme9LXidBYKTzwi803j3q2jSPiqDPKyN+1NOpKOZafP3bTYRve5+bqFQSPyE2aBsMVlbk3lBapmb6qlakpzH39JgWhMMxy5vb+I9WkntggYIxzq8ad6/zFJrDn3R4UNWzCb7p+PL04klmetP5HQDhr4/GOSnVinOYTVOPl8RLOIq+2pHfRhheB4Yo9r1Sf7kaA==",
      "POSTGRES_PASSWORD": "AgAPya8ItvMUH0vrDNycHI4Sw+nZFblLAvWhoQ7M19OqFts5XCzblEzS6l/DuOVVEGI1vVT70yE0zHVL0/1oSDpAhZKGDsBVEP+YcXugZ6qRxGF9qv+AkaM3Csnu1Zju57KSzlXio814/7nTU22sJhFKlZB6VIqdvHgXTTfaJqomnvJsBKZauQckamI3S1dGRrPfN8V7ZOt96KJJT/siWXvHWVXMktu9Ai5NNrb1czcyijlm+c5izeenChNA5kaYide+nhMQMs62GfKu7y5R3EK7UGQvdZAkeILFfKY1jnIcY/o2B9evOROawJHev9wW9JzWgWokKh6/tA8rwl5cOc0AMHnflmsQQ7EjmHH2yS0oOZy94t489sn8sZo/3emIsH5DnCl0Sru7kixMcNG/diYTrKiB/7JsOmLrNrf6Q+sBmiaPoXPLdWzyX1qHi4MWrTl/IbeBrcxhpKg7qUbcLabzmueDVw4ofXBDGcFFca+iBf9uCUujhPMMzZnU1gTQkKyaeZ24uBitXXm0wSoeRwuKqmQChAnyEx64SK62dP2gCOVpeYRysknj+2uq7X4zIzdFrOSqPsaDf+c6ve8+LP7b/FI4eX8HMHwE9oWOEowVSRkDponx+eYqtoGgWft2JX/mEhGvX8yFUFjc70pc3I13ltUKG2BnMD2FmNPn8md5wnYR04nhA38akucVbGUNX6iUCh2qM69YHg==",
      "POSTGRES_USER": "AgCeukv5m2u5pG9bTbi69y5qygaeK9v6jtdutgaN6mSgSxj/IU6pVk9d0w6ZogSg8z8ViA7ft1s0fVodN+oFtUR7JfkufMZVd4v1YrU2cPZc1Xqn4BCH9hpdAtSkETRiyDiVUeArkRmjUWk+m5Ei2pcnZJivdpu1GT9fNUW83OCYL5aRP0l1/CF5hZB+R7EHNBZP3kXptaJAiApi6XYXg9XDLkWrEySvykYE/lXLmQ9MCz5gwb8Vj5qkEK9CN6FdseKxgJqzral61hvM6NGkDJidF5SqQtoDNf/CgYPLUJC2BC4SydxG1i0zdF5BfB57g2ikKHDaFHx6mOv7U0UlvGM6qRLP4jj/E0AuddDidbajXGiq8i8kjmfPff2iMle6m/EV6/V09C61qn97YXCoq5cAAKhMpsLhHNbGq5/UnGhSft9rzClcGUN2lCvI/z2R3s3uFWco2oXChSPOJl4xyisd0fLjdzMy4kG3HnK/qjszsCXa8aR5xbWCY92TCIPXQU4sfO8rM4wj3YJUSeF3bROW5ONpfQIyavmxn064ocyxL6Wfo6lJIKiQZd/9yonKndcNBQrtUopVW4QDlLPr7NQaoxWR7yHEkybJuDVdYZEvDuNF5kTcRH6DYr6nlbOqZIKrZKoMJyR35mtVSmE2usrcdMKs4Q6OBMOyLJiaRHEqiDmEde6nkAGYJFuzfX59jCNO9B9GfnTGGQ=="
    }
  }
}
