apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/tuongndb1609/forum-service
  newName: docker.io/tuongndb1609/forum-service
  newTag: 987c41c944961b15f20bee26219a7745bd646f0b
