{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "auth-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "auth-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "POSTGRES_DB": "AgBVEwbHVnoLet7df/E6zHU8eh8Q4Tw4+j90aEF/7kYkc35yOyDPwQ0D0ct09aJi4KIp0EIg+cM9UDRGnuH1N8+tTGCQ0evp0Ws1jBnAl0eGI9dJB6i7P0r9w8Pd90j7u/Mtf+L8nR9AY0/e7YRbAkExdjtxvI9PID6dwtZF63qCSCi4wziax+3YM7v7jRTxv80APaYD/hTWmC5fEIMXhxXhVZ00B3+qRraMyJHiIhiKVUxb/ept2ozLDM7PJH61M8DWhX3yyM/gmSDHA7VOZ6WxyzGUIbSe+ox7DXfu9WN3aatUTE4F1tnGqE9g1eN2sOfSVtL5hiBBH8eDwJXFja5Y8ukhfi/+kAdAUHrR/0P9fB8JbfJGT+3dGs2wODu5nKhlbtZvHNwMTVNywC881x0SaYxIF1xDU26SVISHTu7mq/DHCfQs/WzGledtRHsI8XcukhVZ2jmWgf04bPVU1lrd30PGcOfrQQRXKbm7mV3ooCSNRsWtCRsONceONa1wQ4GpVNhpDG/HFN4bPWZf79kbnU6WFOP59UbDO/2SIqFL2SUAUeNxuHGP3QFyPlg450NkjmRK2JdTkgcaYXIbnH2cqlSLLK0NGk01s5LgbcgmbpFn5thYyexvuSM52SHeVOnzOiWRVIwqxdUHzvFU/a63IXCEaltmXhmG5W4/cEStG8kSMkG93ylptIMa3OqfXc/Tx0B8npo2",
      "POSTGRES_PASSWORD": "AgA+jDfwuuQoIGfHBSGA4wlI5PG81wBvzS4ZyNgFrj7mgDyoW2/Sg7sgJxjfuty8eq2Z9ULWf7Pp/ze2qFwcvFhzC3Ulqu0Q9ak0okQhDFxw1j05PbFNF99YUb62uBunAUObLDhJFSxmLOGpJzrtrhMJ/jOS8yoaNj/Z8YryoOw9Vg/euti6AQynDjy3BhSQDs0fouqfgT2+H9y/aKalBcMJthFUik5LGXWOjScaktAstMnm4s+cWsZYBMnxvH3Fmp1hL5PWCHK/oRX6qCS+EqfKwV+rWdXuUf3y+QZd0q3b79/JVjOYXKQJnBNjGNNhMHW4RuxwinzXf98MO/WH4ElVpff7rL5IIkTjZyE1BR5yOVG2A4lPRut/83cKKumxzevyIIH8SKlb3LWnCtv9eG4T3Te3QVfI7Yig2amc4Opow7YnLe2Ql+Powhi32kMgPwXvsEB0NeYv3Nx4yJszeMiVQzza/cL4M33WNEYFGR1Ao/6GXXceZgHhCe3BKqYvoSf7isdmKxHb4+tAK9Tvox1TJuCZk6v1L6Yd2F0P3RdyVssz61K974SR9ShEdnAh8rs0nTRg+2ArpspYoTOuloxngD0XSpRdMuuz36/eVdN9HoPlNP0k2Hu5R9lpwWOmYhhxsoUkyP1FvVrVWabeJ4NGLbvLj0Wza3EniQiD3fEvRL998F+go7rz29UN6qypPF++zAs3cdTiDg==",
      "POSTGRES_USER": "AgBnn7nRsLJPBCk2kCS5v5uOtPWorGbSxmwO/mgr2TOApghHl07m7mw6BWJFmbwoS9Lb0xPxTh391wa0zWKmlSDrU0sp2VmUs+qv4/2fHl+Ngiz49yWHtxBUyGRadBR/ZYGa3x1jHnLkd+tvAdKNKToEWmTEOdfSRKYjJ/LZ1+8j2WM+JB4ty2htXT64RqdtM4SBoYlE4itLZvOmlBbKcYTt0Hm5PwwV357puSMu6+KOHeM4kMfCHPr8t1Ktlt5Ja+IhQKFSXtE8HSSw0OI7Q2/X7clrVC9//kp7W9noLwCbNOB79/7PWQkJbJo+RCIKrj4DEPxOGpvH+m00Fm/e4lJS2vW6kDe9vB7sRuuiCtlewHuXnm47qHRnc9kGWe5uYs8aEteGGzFSDlEXw0kDc86v8f0mcTB/rA9NDkdDRncIJkltstLWEGuZDB8vPafRBJxAhi9Z4wxT5vonh5iKW1R//QbWuHjIZ+o0fVYcENkVxypiHcvoZLvQ4NHaaOQftuYSwjLd3ZC68Li3h0Li2RLLkPVln28hcMeNbjZKqRR85T3uOQwAmZessfhwS8bsqcFs9wVuw5BhYEjCsOXSR5QTYd/LWq6vUKq6wHbkYrJQ1XD6jzjGXBKjxRxO8TKHVaF722oNUkVqGWLW9wT+8oHfRV5D+aqhRfw8YxygvCuDiIS3mrU7P/E+96pTsvxJ2zaXFKqywNojng=="
    }
  }
}
