version: '3.8'

services:
  forum-db: 
    image: postgres:17-alpine 
    container_name: forum-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: forum_db
    ports:
      - "5434:5432"
    volumes:
      - ./forum_data:/var/lib/postgresql/data